---
title: "Learning Journal Template"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format: html
editor: visual
---

## Section 1: ESRI Tutorials, Lessons and Certificates

Tutorial name(s) and link(s):

Insight:

Screenshot(s):

-   Tutorial final map:
-   Certificate when applicable (weeks 4,8,10)

New Tools and Processes: The goal is to record information on the tools you learned and why that tool was used in the given situation. (The number of new tools and processes you include will change from week to week. Strive to have a minimum of 5; include as many more than 5 as will be helpful to you in the future.)

| NEW Tool/Process                                 | Tool/Process Results                                                         | Purpose                                          |
|--------------------------------------------------|------------------------------------------------------------------------------|--------------------------------------------------|
| List of the new tools or processes introduced in 
 this Professional Learning                        | Describe the results including whether it adds                               
                                                    new data to the geodatabase. When helpful to you, include a mini-screenshot.  | Explain the reason this tool or process was used 
                                                                                                                                   in this situation.                                |
|                                                  |                                                                              |                                                  |
|                                                  |                                                                              |                                                  |
|                                                  |                                                                              |                                                  |
|                                                  |                                                                              |                                                  |
|                                                  |                                                                              |                                                  |

Answers to questions when applicable (e.g., Week 8)

## Section 2: Data Sources

Knowing where to find and download geospatial data can be a big challenge. In this section, list the internet data sources that you use during the semester and any others that you encounter on your own.

## Section 3: Class How Tos

In this section include documents provided in class (e.g., how to prepare a table for use in GIS, how to georeference) or notes about a specific tool you learn about that's not part of the assigned topics.
